name: "export" # name of the workflow
on: # when it is triggered
  workflow_dispatch: # manually
  push: # on push
    paths: # with modifications to these files
      - "**.gd"
      - "**.tscn"
      - "**.import"
      - "**.tres"
      - "**.ttf"
      - ".github/workflows/export.yml"
      - "export_presets.cfg"
    branches: # on this branch
      - main

jobs: # the things to do
  export: # a thing to do
    uses: bend-n/godot-actions/.github/workflows/callable-export.yml@main
    with: # variables
      export-name: ${{ github.event.repository.name }} # the name of the zipfile
      godot-version: 3.5 # the godot version
      image: ghcr.io/bend-n/godot-2d:3.5 # the container to use
      platforms: "windows linux web android mac" # space seperated list of platforms to build
    secrets: # secrets
      android-keystore-base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }} # not required
      android-keystore-password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }} # not required
      butler-api-key: ${{ secrets.BUTLER_CREDENTIALS }} # required for itch.io
